version = 0.1

[default.deploy.parameters]
stack_name = "imagekit-mcp-server"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "imagekit-mcp-server"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
